# Gradle
org.gradle.daemon                    = true
org.gradle.jvmargs                   = -Xmx3G
org.gradle.parallel                  = true
org.gradle.caching                   = true
org.gradle.java.home                 = /usr/lib/jvm/java-25-openjdk
name                                 = Devly

# Common
java_version                         = 25
hytale_version                       = 0.+
manifestServerVersion                = >=0.5.0 <0.7.0
release_type                         = PRERELEASE
maven_url                            = https://maven.azuredoom.com/mods
hmod_maven_url                       = https://maven.hytalemodding.dev/releases

# Publishing
modtale_uuid                         = 6a5e2a70-6c71-4820-a271-f8c3445a8311
modifold_id                          = VsC9Ag
curseforgeID                         = 1668661

# Mod options
group                                = com.riprod.devly
manifest_group                       = Riprod
mod_name                             = Devly
main_class                           = com.riprod.devly.DevlyPlugin
mod_author                           = Riprod
mod_id                               = Devly
mod_license                          = GPLv3
mod_description                      = Patchly Development extension for patchly utils during file fabrication
mod_credits                          = Riprod
mod_logo                             = icon-256.png
mod_url                              = https://modtale.net/mod/devly
mod_issues                           = https://github.com/itsriprod/devly/issues
mod_sources                          = https://github.com/itsriprod/devly
version                              = 1.0.1
includes_pack                        = true
disabled_by_default                  = false
patchline                            = prerelease
load_user_mods                       = false
manifest_dependencies                = Riprod:Patchly=*
manifest_opt_dependencies            = 